services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST:-localhost}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-api_gateway}
    networks:
      - api-network
    volumes:
      - api-v2-data:/var/lib/api-gateway
      - ./src/apps/dynamics/utils/logs/dynamics_sync:/app/logs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  api-network:
    driver: bridge

volumes:
  api-v2-data:
    driver: local